<?xml version="1.0" encoding="UTF-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup Condition="$(ProduceOnlyReferenceAssembly) == 'True' OR $(ProduceReferenceAssembly) == 'True'">
        <CopyLocalLockFileAssemblies>False</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    
    <Import Condition="Exists('$(BasePath)..\RhinoCode.targets')" Project="$(BasePath)..\RhinoCode.targets" />
</Project>
